"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { WriteVerification } from "@/components/abuse/TurnstileCheck";
import { inputCls } from "@/components/wizard/Field";
type Update = {id:string;title:string;body:string;created_at:string};
export function ProjectUpdates({projectId,owner,initial}:{projectId:string;owner:boolean;initial:Update[]}) {
 const [items,setItems]=useState(initial),[title,setTitle]=useState(""),[body,setBody]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false);
 async function post(e:React.FormEvent){e.preventDefault();if(!confirm("Post this update to your project and notify your followers?"))return;setBusy(true);setNote("");const sb=createClient();const {data:auth}=await sb.auth.getUser();const {data,error}=await sb.from("project_updates").insert({project_id:projectId,author_id:auth.user?.id,title:title.trim(),body:body.trim()}).select("id,title,body,created_at").single();setBusy(false);if(error)return setNote("Could not post. Complete the security check and try again.");setItems([data,...items]);setTitle("");setBody("");}
 return <section className="mt-10" aria-labelledby="updates"><h2 id="updates" className="text-xl font-bold">Project updates</h2><p className="mt-1 text-sm text-muted">What changed since launch.</p>{owner&&<form onSubmit={post} className="mt-4 space-y-3 rounded-2xl border border-line bg-paper p-5"><input aria-label="Update title" className={inputCls} placeholder="What did you ship?" value={title} onChange={e=>setTitle(e.target.value)} maxLength={100} required/><textarea aria-label="Update details" className={inputCls} placeholder="Share the progress, fix or milestone." value={body} onChange={e=>setBody(e.target.value)} maxLength={2000} required/><WriteVerification/><button disabled={busy||!title.trim()||!body.trim()} className="rounded-full bg-terracotta px-5 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy?"Posting...":"Post update"}</button><p className="text-xs text-muted">Your followers get an in-app notification.</p>{note&&<p role="alert" className="text-sm text-terracotta">{note}</p>}</form>}<ol className="mt-5 space-y-4">{items.map(u=><li key={u.id} className="rounded-2xl border border-line bg-paper p-5"><p className="text-xs text-muted">{new Date(u.created_at).toLocaleDateString("en-IN")}</p><h3 className="mt-2 font-bold">{u.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-relaxed text-muted">{u.body}</p></li>)}</ol>{!items.length&&<p className="mt-5 text-sm text-muted">No updates yet.</p>}</section>;
}
