"use client";
import { useState } from "react";
import { Icon } from "@/components/ui/Icon";
import { inputCls } from "./Field";
import type { Draft } from "./types";
type Repo={id:number;name:string;private:boolean};
export function GitHubImport({apply}:{apply:(d:Partial<Draft>)=>void}){
 const [repos,setRepos]=useState<Repo[]>([]),[id,setId]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[login,setLogin]=useState(""),[install,setInstall]=useState("");
 async function list(){setBusy(true);setNote("");try{const res=await fetch("/api/github/import");const data=await res.json();if(!res.ok)setNote(data.error);else{setRepos(data.repos);setLogin(data.login);setLoaded(true);setInstall(data.installUrl??"");setNote(!data.installed?"Install the GitHub App to choose which repositories appear.":!data.all?"Showing the repositories you selected. Choose All repositories in GitHub to include every owned repo.":!data.repos.length?"No owned repositories found.":"");}}catch{setNote("Could not connect. Try again.");}setBusy(false);}
 async function load(){setBusy(true);setNote("");try{const res=await fetch("/api/github/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:Number(id)})});const data=await res.json();if(!res.ok)setNote(data.error);else{apply({title:data.title,pitch:data.pitch,description:data.description,repoUrl:data.repoUrl,demoUrl:data.demoUrl,privateSource:data.privateSource,privateReviewed:false});setNote(data.privateSource?"Private source: draft only. Repository and homepage links are omitted. Review the imported text before publishing.":"Imported into your draft. Review the fields and add screenshots before publishing.");}}catch{setNote("Could not connect. Try again.");}setBusy(false);}
 return <section className="mb-6 rounded-2xl border border-sage bg-[#e9eed9] p-4"><h3 className="flex items-center gap-2 text-sm font-bold"><Icon name="github"/>Start from your GitHub</h3><p className="mt-1 text-xs text-muted">Your own public and private repositories, with your permission. Repository details only, no code access or edits.</p><div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={busy} onClick={list} className="rounded-xl bg-olive px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy?"Loading...":loaded?"Refresh repositories":"Load my repositories"}</button><a className="text-xs underline" href="/api/github/connect">Connect GitHub</a>{install&&<a className="text-xs underline" href={install}>Choose repository access</a>}</div>{loaded&&<div className="mt-3 flex gap-2"><select aria-label={`Repositories owned by ${login}`} className={inputCls} value={id} onChange={e=>setId(e.target.value)}><option value="">Choose your repository</option>{repos.map(r=><option key={r.id} value={r.id}>{login}/{r.name}{r.private?" (private)":""}</option>)}</select><button type="button" disabled={busy||!id} onClick={load} className="rounded-xl bg-olive px-4 text-sm font-semibold text-white disabled:opacity-40">Import</button></div>}{note&&<p role="status" className="mt-2 text-xs text-muted">{note}</p>}</section>;
}
