"use client";
import { useState } from "react";
import { Icon } from "@/components/ui/Icon";
import { inputCls } from "./Field";
import type { Draft } from "./types";
type Repo={name:string;description:string|null};
export function GitHubImport({apply}:{apply:(d:Partial<Draft>)=>void}){
 const [repos,setRepos]=useState<Repo[]>([]),[name,setName]=useState(""),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[login,setLogin]=useState("");
 async function list(){setBusy(true);setNote("");try{const res=await fetch("/api/github/import");const data=await res.json();if(!res.ok)setNote(data.error);else{setRepos(data.repos);setLogin(data.login);setLoaded(true);setNote(data.repos.length?data.more?"Showing your 100 most recently updated public repositories.":"":"No public repositories found on your GitHub account.");}}catch{setNote("Could not connect. Try again.");}setBusy(false);}
 async function load(){setBusy(true);setNote("");try{const res=await fetch("/api/github/import",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name})});const data=await res.json();if(!res.ok)setNote(data.error);else{apply({title:data.title,pitch:data.pitch,description:data.description,repoUrl:data.repoUrl,demoUrl:data.demoUrl});setNote("Imported into your draft. Review the fields and add screenshots before publishing.");}}catch{setNote("Could not connect. Try again.");}setBusy(false);}
 return <section className="mb-6 rounded-2xl border border-sage bg-[#e9eed9] p-4"><h3 className="flex items-center gap-2 text-sm font-bold"><Icon name="github"/>Start from your GitHub</h3><p className="mt-1 text-xs text-muted">Only public repositories owned by your signed-in GitHub account. No private-repo access. Nothing is published.</p>{!loaded?<div className="mt-3 flex flex-wrap items-center gap-3"><button type="button" disabled={busy} onClick={list} className="rounded-xl bg-olive px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy?"Loading...":"Load my repositories"}</button><a className="text-xs underline" href="/login?provider=github&next=%2Fnew">Sign in with GitHub</a></div>:<div className="mt-3 flex gap-2"><select aria-label={`Public repositories owned by ${login}`} className={inputCls} value={name} onChange={e=>setName(e.target.value)}><option value="">Choose your repository</option>{repos.map(r=><option key={r.name} value={r.name}>{login}/{r.name}</option>)}</select><button type="button" disabled={busy||!name} onClick={load} className="rounded-xl bg-olive px-4 text-sm font-semibold text-white disabled:opacity-40">{busy?"Reading...":"Import"}</button></div>}{note&&<p role="status" className="mt-2 text-xs text-muted">{note}</p>}</section>;
}
