import type {AdminData} from "@/lib/admin/types";
import {ModerationControl} from "./ModerationControl";
import {AnnouncementEditor} from "./AnnouncementEditor";
const box="rounded-2xl border border-line bg-paper p-6";
export function ReferencePanels({tab,d}:{tab:string;d:AdminData}){
 if(tab==="content") return <><AnnouncementEditor/><p className="mb-4 text-sm text-muted">Published banners appear above the feed. Save drafts first; publishing needs a second confirmation.</p><div className="space-y-3">{d.announcements.map(a=><article key={a.id} className={box}><h2 className="font-bold">{a.title}</h2><p className="my-3 whitespace-pre-wrap">{a.body}</p><p className="mb-3 text-xs text-muted capitalize">{a.state}</p><ModerationControl kind="announcement" target={a.id} decision={a.state==="published"?"unpublish":"publish"} label={a.state==="published"?"Unpublish":"Publish to feed"}/></article>)}</div><section className={`${box} mt-6`}><h2 className="text-xl font-bold">Categories</h2><p className="mt-2 text-sm text-muted">Topics come from project tags. No made-up categories or empty pages.</p><ul className="mt-4 flex flex-wrap gap-3">{d.categories.map(c=><li key={c.tag} className="rounded-full bg-[#e9eed9] px-3 py-2 text-sm">{c.tag} · {c.projects}</li>)}</ul></section></>;
 if(tab==="analytics") return <section className={box}><h2 className="text-xl font-bold">Last 7 days</h2><p className="mt-2 text-sm text-muted">Actual project and builder records. Includes demo data until prelaunch cleanup. No traffic tracking is connected.</p><div className="mt-6 space-y-4">{d.activity.map(a=><div key={a.day}><div className="flex justify-between gap-3 text-xs"><span>{a.day}</span><span>{a.projects} projects · {a.builders} builders</span></div><div className="mt-2 h-3 rounded-full bg-cream"><div className="h-3 rounded-full bg-sage" style={{width:`${Math.max(2,a.projects/Math.max(1,...d.activity.map(x=>x.projects))*100)}%`}}/></div></div>)}</div></section>;
 if(tab==="payments") return <section className={box}><h2 className="text-xl font-bold">No payment system connected</h2><p className="mt-3 leading-7 text-muted">ShipStory is free. There are no charges, refunds, failed transactions or commissions to manage. Those controls will need a payment provider and a reviewed billing plan before they can be enabled.</p></section>;
 if(tab==="access") return <section className={box}><h2 className="text-xl font-bold">Team access</h2><p className="mt-3 text-muted">Owner admin only. No extra team members have been invited.</p>{d.admins.map(a=><p key={a.handle} className="mt-4 rounded-xl bg-[#e9eed9] p-4 font-semibold text-olive">@{a.handle} · Owner admin</p>)}<p className="mt-5 text-sm text-muted">Adding another admin needs a named account and your approval. Builder verification is a manual review badge, not identity verification.</p></section>;
 return null;
}
