import Link from "next/link";
import { redirect } from "next/navigation";
import { AppNav } from "@/components/layout/AppNav";
import { ReferencePanels } from "@/components/admin/ReferencePanels";
import { ModerationControl } from "@/components/admin/ModerationControl";
import { adminAccess } from "@/lib/admin/access";
import type { AdminData } from "@/lib/admin/types";
export const dynamic = "force-dynamic";
const tabs = ["overview","projects","reports","builders","content","analytics","payments","access"];
export default async function Admin({searchParams}: {searchParams: Promise<{tab?: string; q?: string}>}) {
 const {sb,user,allowed} = await adminAccess();
 if (!user) redirect("/login?next=/admin");
 if (!allowed) return <><AppNav/><main className="mx-auto max-w-xl px-5 py-20"><h1 className="text-3xl font-extrabold">Admin access only</h1><p className="mt-3 text-muted">This account does not have access to ShipStory administration.</p><Link className="mt-5 inline-block text-terracotta" href="/feed">Back to feed</Link></main></>;
 const {data,error} = await sb.rpc("admin_overview");
 if (error || !data) return <><AppNav/><main className="p-10"><h1 className="text-2xl font-bold">Admin data unavailable</h1><p role="alert" className="mt-3">Refresh to try again. No changes have been made.</p></main></>;
 const d = data as AdminData; const params = await searchParams; const tab = tabs.includes(params.tab ?? "") ? params.tab! : "overview"; const q = (params.q ?? "").slice(0,100).toLowerCase();
 const projects = d.projects.filter(p=>`${p.title} ${p.owner} ${p.status}`.toLowerCase().includes(q));
 const builders = d.builders.filter(b=>`${b.handle} ${b.display_name}`.toLowerCase().includes(q));
 const reports = d.reports.filter(r=>`${r.reason} ${r.reporter} ${r.project_title} ${r.review_status}`.toLowerCase().includes(q));
 return <><AppNav/><main className="mx-auto max-w-[1400px] px-5 py-8 lg:px-8"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><span className="text-xs font-semibold uppercase tracking-[.18em] text-olive">Your workspace</span><h1 className="mt-2 text-4xl font-extrabold tracking-tight">Keep good things growing.</h1><p className="mt-3 text-muted">ShipStory admin. Review reports, manage visibility, see what is growing.</p></div><span className="rounded-full border border-line bg-[#e9eed9] px-4 py-2 text-xs font-semibold text-olive">Admin · {user.email}</span></div>
 <div className="grid gap-6 lg:grid-cols-[205px_minmax(0,1fr)]"><aside className="h-fit rounded-2xl border border-line bg-paper p-3 shadow-soft"><nav aria-label="Admin sections" className="flex flex-wrap gap-2 lg:flex-col">{tabs.map(t=><Link key={t} href={`/admin?tab=${t}`} aria-current={tab===t ? "page" : undefined} className={`rounded-xl px-4 py-3 text-sm font-semibold capitalize ${tab===t ? "bg-[#e9eed9] text-olive" : "text-muted hover:bg-cream"}`}>{t}{t==="reports" && d.counts.reports>0 ? ` · ${d.counts.reports}` : ""}</Link>)}</nav><p className="mt-5 hidden border-t border-line px-4 pt-4 text-xs leading-relaxed text-muted lg:block">Private preview<br/>No public launch yet.</p></aside><section className="min-w-0">
 {tab==="overview" ? <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Projects",d.counts.projects],["Builders",d.counts.builders],["Open reports",d.counts.reports],["Reserved images",`${d.counts.reserved_slots} / 160`]].map(([label,value])=><div key={label} className="rounded-2xl border border-line bg-paper p-5 shadow-soft"><p className="text-xs font-semibold uppercase tracking-wider text-muted">{label}</p><p className="mt-3 text-3xl font-extrabold">{value}</p></div>)}</div><div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-line bg-paper p-6"><h2 className="text-xl font-bold">Review queue</h2><p className="mt-3 text-muted">{d.counts.reports ? `${d.counts.reports} reports need a look.` : "All clear. No open reports."}</p><Link href="/admin?tab=reports" className="mt-5 inline-block rounded-xl bg-terracotta px-4 py-2 text-sm font-semibold text-white">Review reports</Link></div><div className="rounded-2xl border border-line bg-paper p-6"><h2 className="text-xl font-bold">Free-tier guardrails</h2><p className="mt-3 text-sm leading-7 text-muted">20 image slots per builder. 160 across ShipStory. Each image is limited to 5 MiB. Reservations stay counted after deletion or failed uploads until reviewed cleanup.</p></div></div><div className="mt-6 rounded-2xl border border-line bg-paper p-6"><h2 className="text-xl font-bold">Recent admin activity</h2>{d.actions.length ? <ul className="mt-4 divide-y divide-line">{d.actions.map((a,i)=><li key={i} className="flex flex-wrap justify-between gap-2 py-3 text-sm"><span className="capitalize">{a.target_kind} · {a.action}</span><time className="text-muted">{new Date(a.created_at).toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})}</time></li>)}</ul> : <p className="mt-3 text-muted">No moderation changes yet. Actions will appear here.</p>}</div></> : <><ReferencePanels tab={tab} d={d}/>{["projects","builders","reports"].includes(tab) && <form className="mb-5 flex gap-3"><input type="hidden" name="tab" value={tab}/><input aria-label={`Search ${tab}`} name="q" defaultValue={params.q} maxLength={100} placeholder={`Search ${tab}...`} className="min-w-0 flex-1 rounded-xl border border-line bg-paper px-4 py-3 outline-none focus:ring-2 focus:ring-sage"/><button className="rounded-xl bg-olive px-5 text-sm font-semibold text-white">Search</button></form>}{["projects","builders","reports"].includes(tab) && <p className="mb-4 text-xs text-muted">Latest 100 records. Counts on Overview include all records.</p>}
 {tab==="projects" && <div className="space-y-3">{projects.map(p=><article key={p.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-line bg-paper p-5"><div className="min-w-0 flex-1"><h2 className="font-bold">{p.title}</h2><p className="mt-1 text-sm text-muted">@{p.owner} · {p.moderated_hidden ? "Hidden by admin" : p.status}</p><p className="mt-2 text-sm">{p.tagline}</p></div><ModerationControl kind="project" target={p.id} decision={p.moderated_hidden ? "restore" : "hide"} label={p.moderated_hidden ? "Restore" : "Hide"}/>{!p.moderated_hidden && <Link href={`/p/${p.slug}`} className="text-xs font-semibold text-terracotta">View project</Link>}</article>)}{!projects.length && <Empty label="No projects match."/>}</div>}
 {tab==="builders" && <div className="space-y-3">{builders.map(b=><article key={b.id} className="flex flex-wrap justify-between gap-3 rounded-2xl border border-line bg-paper p-5"><div><Link href={`/u/${b.handle}`} className="font-bold">@{b.handle}</Link><p className="mt-1 text-sm text-muted">{b.display_name} {b.admin_verified ? "· Reviewed" : ""} {b.posting_blocked ? "· Posting blocked" : ""}</p></div><p className="text-sm text-muted">{b.projects} projects · {b.reserved_slots} / 20 image slots</p><div className="flex gap-2"><ModerationControl kind="builder" target={b.id} decision={b.posting_blocked?"unblock":"block"} label={b.posting_blocked?"Unblock posting":"Block posting"}/><ModerationControl kind="builder" target={b.id} decision={b.admin_verified?"unverify":"verify"} label={b.admin_verified?"Remove review badge":"Mark reviewed"}/></div></article>)}{!builders.length && <Empty label="No builders match."/>}</div>}
 {tab==="reports" && <div className="space-y-4">{reports.map(r=><article key={r.id} className="rounded-2xl border border-line bg-paper p-5"><div className="flex flex-wrap justify-between gap-2"><h2 className="font-bold">{r.project_title || "Unavailable content"}</h2><span className="rounded-full bg-[#e9eed9] px-3 py-1 text-xs capitalize text-olive">{r.review_status}</span></div><p className="mt-2 text-sm text-muted">{r.reason} · reported by @{r.reporter}</p>{r.comment_body && <blockquote className="mt-3 border-l-2 border-sage pl-3 text-sm">{r.comment_body}</blockquote>}<p className="mt-3 whitespace-pre-wrap text-sm">{r.details || "No extra details."}</p><div className="mt-4 flex flex-wrap gap-3">{r.review_status==="open" ? <><ModerationControl kind="report" target={r.id} decision="resolved" label="Resolve"/><ModerationControl kind="report" target={r.id} decision="dismissed" label="Dismiss"/></> : <ModerationControl kind="report" target={r.id} decision="open" label="Reopen"/>}{(r.comment_id || r.project_id) && <><ModerationControl kind={r.comment_id ? "comment" : "project"} target={(r.comment_id || r.project_id)!} decision="hide" label="Hide content"/><ModerationControl kind={r.comment_id ? "comment" : "project"} target={(r.comment_id || r.project_id)!} decision="restore" label="Restore content"/></>}</div></article>)}{!reports.length && <Empty label="No reports. A little breathing room."/>}</div>}</>}
 </section></div></main></>;
}
function Empty({label}: {label:string}) {return <div className="rounded-2xl border border-dashed border-line p-10 text-center text-muted">{label}</div>;}
